"""Initial migration - create all tables

Revision ID: 502160f9945d
Revises: 
Create Date: 2025-11-04 08:44:29.755518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502160f9945d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='User first name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='User last name'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='User phone number'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Company name (for GROSSISTE)'),
    sa.Column('role', sa.Enum('ADMIN', 'RESPONSABLE_LOGISTIQUE', 'OPERATEUR_USINE', 'CHAUFFEUR', 'GROSSISTE', name='user_role'), nullable=False, comment='User role for RBAC'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user account is active'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether user email is verified'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique audit log identifier'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed the action'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Action performed (CREATE, UPDATE, DELETE, etc.)'),
    sa.Column('resource_type', sa.String(length=100), nullable=False, comment='Type of resource affected'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='ID of the affected resource'),
    sa.Column('changes', sa.JSON(), nullable=True, comment='JSON object with before/after values'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address of the request'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User agent string'),
    sa.Column('endpoint', sa.String(length=255), nullable=True, comment='API endpoint accessed'),
    sa.Column('http_method', sa.String(length=10), nullable=True, comment='HTTP method used'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='When action was performed'),
    sa.Column('success', sa.String(length=10), nullable=False, comment='Whether the action was successful'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if action failed'),
    sa.Column('additional_data', sa.JSON(), nullable=True, comment='Additional contextual data'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_timestamp', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_endpoint'), 'audit_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_success'), 'audit_logs', ['success'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_success_timestamp', 'audit_logs', ['success', 'timestamp'], unique=False)
    op.create_index('ix_audit_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('expeditions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique expedition identifier'),
    sa.Column('reference_number', sa.String(length=100), nullable=False, comment='Unique reference number'),
    sa.Column('status', sa.Enum('CREATION', 'EN_ATTENTE', 'CREEE', 'EN_TRANSIT', 'ARRIVEE', 'LIVREE', 'PROBLEME', 'ANNULEE', name='expedition_status'), nullable=False, comment='Current status in workflow'),
    sa.Column('date_creation', sa.DateTime(), nullable=False, comment='Date expedition was created'),
    sa.Column('date_departure', sa.DateTime(), nullable=True, comment='Date expedition departed'),
    sa.Column('eta', sa.DateTime(), nullable=True, comment='Estimated time of arrival'),
    sa.Column('date_arrival', sa.DateTime(), nullable=True, comment='Actual arrival date'),
    sa.Column('date_delivery', sa.DateTime(), nullable=True, comment='Date delivery was completed'),
    sa.Column('transporter', sa.String(length=255), nullable=True, comment='Name of transport company/driver'),
    sa.Column('vehicle_info', sa.String(length=255), nullable=True, comment='Vehicle information (plate, type, etc.)'),
    sa.Column('destination_address', sa.String(length=500), nullable=False, comment='Delivery address'),
    sa.Column('destination_contact', sa.String(length=255), nullable=True, comment='Contact person at destination'),
    sa.Column('destination_phone', sa.String(length=20), nullable=True, comment='Contact phone at destination'),
    sa.Column('notes', sa.String(length=1000), nullable=True, comment='Additional notes'),
    sa.Column('problem_description', sa.String(length=1000), nullable=True, comment='Description if status is PROBLEME'),
    sa.Column('otp_code', sa.String(length=10), nullable=True, comment='One-time password for delivery validation'),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True, comment='OTP expiration time'),
    sa.Column('palette_count', sa.Integer(), nullable=False, comment='Number of palettes in expedition'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='User who created the expedition'),
    sa.Column('validated_by_id', sa.UUID(), nullable=True, comment='User who validated the expedition'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expeditions_created_at'), 'expeditions', ['created_at'], unique=False)
    op.create_index(op.f('ix_expeditions_created_by_id'), 'expeditions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_expeditions_date_creation'), 'expeditions', ['date_creation'], unique=False)
    op.create_index(op.f('ix_expeditions_date_delivery'), 'expeditions', ['date_delivery'], unique=False)
    op.create_index(op.f('ix_expeditions_date_departure'), 'expeditions', ['date_departure'], unique=False)
    op.create_index('ix_expeditions_dates', 'expeditions', ['date_departure', 'eta'], unique=False)
    op.create_index(op.f('ix_expeditions_eta'), 'expeditions', ['eta'], unique=False)
    op.create_index(op.f('ix_expeditions_id'), 'expeditions', ['id'], unique=False)
    op.create_index('ix_expeditions_ref_status', 'expeditions', ['reference_number', 'status'], unique=False)
    op.create_index(op.f('ix_expeditions_reference_number'), 'expeditions', ['reference_number'], unique=True)
    op.create_index(op.f('ix_expeditions_status'), 'expeditions', ['status'], unique=False)
    op.create_index('ix_expeditions_status_dates', 'expeditions', ['status', 'date_creation'], unique=False)
    op.create_index(op.f('ix_expeditions_validated_by_id'), 'expeditions', ['validated_by_id'], unique=False)
    op.create_table('palettes',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique palette identifier'),
    sa.Column('rfid_tag', sa.String(length=50), nullable=False, comment='Unique RFID tag identifier'),
    sa.Column('type', sa.Enum('B6', 'B12', 'B28', name='palette_type'), nullable=False, comment='Type of gas bottles (B6, B12, B28)'),
    sa.Column('status', sa.Enum('CREATION', 'EN_STOCK', 'EN_ROUTE', 'EN_RECEPTION', 'LIVREE', 'RETOURNEE', 'OUT', name='palette_status'), nullable=False, comment='Current status in workflow'),
    sa.Column('location_latitude', sa.Float(), nullable=True, comment='Current GPS latitude'),
    sa.Column('location_longitude', sa.Float(), nullable=True, comment='Current GPS longitude'),
    sa.Column('location_address', sa.String(length=500), nullable=True, comment='Current address'),
    sa.Column('notes', sa.String(length=1000), nullable=True, comment='Additional notes about palette'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='User who created the palette'),
    sa.Column('current_expedition_id', sa.UUID(), nullable=True, comment='Current expedition if in transit'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_expedition_id'], ['expeditions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_palettes_created_at'), 'palettes', ['created_at'], unique=False)
    op.create_index(op.f('ix_palettes_created_by_id'), 'palettes', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_palettes_current_expedition_id'), 'palettes', ['current_expedition_id'], unique=False)
    op.create_index('ix_palettes_expedition', 'palettes', ['current_expedition_id'], unique=False)
    op.create_index(op.f('ix_palettes_id'), 'palettes', ['id'], unique=False)
    op.create_index('ix_palettes_rfid_status', 'palettes', ['rfid_tag', 'status'], unique=False)
    op.create_index(op.f('ix_palettes_rfid_tag'), 'palettes', ['rfid_tag'], unique=True)
    op.create_index(op.f('ix_palettes_status'), 'palettes', ['status'], unique=False)
    op.create_index(op.f('ix_palettes_type'), 'palettes', ['type'], unique=False)
    op.create_index('ix_palettes_type_status', 'palettes', ['type', 'status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique notification identifier'),
    sa.Column('type', sa.Enum('ALERTE_RETARD', 'ANOMALIE_RFID', 'DIVERGENCE_RECEPTION', 'CONFIRMATION_LIVRAISON', 'EXPEDITION_CREEE', 'EXPEDITION_DEPART', 'EXPEDITION_ARRIVEE', 'PROBLEME_EXPEDITION', 'VALIDATION_REQUISE', 'RETOUR_PALETTE', name='notification_type'), nullable=False, comment='Type of notification'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRYING', name='notification_status'), nullable=False, comment='Delivery status'),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'BOTH', name='notification_channel'), nullable=False, comment='Delivery channel'),
    sa.Column('recipient_email', sa.String(length=255), nullable=True, comment='Recipient email address'),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True, comment='Recipient phone number'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Notification subject/title'),
    sa.Column('message', sa.Text(), nullable=False, comment='Notification message content'),
    sa.Column('expedition_id', sa.UUID(), nullable=True, comment='Related expedition (optional)'),
    sa.Column('palette_id', sa.UUID(), nullable=True, comment='Related palette (optional)'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='When notification was sent'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('retry_count', sa.String(length=10), nullable=False, comment='Number of retry attempts'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['palette_id'], ['palettes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_expedition_id'), 'notifications', ['expedition_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_palette_id'), 'notifications', ['palette_id'], unique=False)
    op.create_index('ix_notifications_recipient', 'notifications', ['recipient_email', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_email'), 'notifications', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_notifications_sent_at'), 'notifications', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_status_created', 'notifications', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_type_status', 'notifications', ['type', 'status'], unique=False)
    op.create_table('palette_movements',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique movement identifier'),
    sa.Column('palette_id', sa.UUID(), nullable=False, comment='Related palette'),
    sa.Column('expedition_id', sa.UUID(), nullable=True, comment='Related expedition (optional)'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed the action'),
    sa.Column('action', sa.Enum('CREATION', 'SCANNING_DEPART', 'SCANNING_ARRIVEE', 'VALIDATION_RECEPTION', 'UPDATE_LOCATION', 'STATUS_CHANGE', 'ASSIGNATION_EXPEDITION', 'RETOUR_USINE', 'MISE_HORS_SERVICE', name='movement_action'), nullable=False, comment='Type of action performed'),
    sa.Column('status_before', sa.String(length=50), nullable=True, comment='Status before action'),
    sa.Column('status_after', sa.String(length=50), nullable=True, comment='Status after action'),
    sa.Column('location', sa.String(length=500), nullable=True, comment='Location where action was performed'),
    sa.Column('latitude', sa.String(length=50), nullable=True, comment='GPS latitude'),
    sa.Column('longitude', sa.String(length=50), nullable=True, comment='GPS longitude'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='When action was performed'),
    sa.Column('details', sa.JSON(), nullable=True, comment='Additional details (JSON)'),
    sa.Column('notes', sa.String(length=1000), nullable=True, comment='Additional notes'),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['palette_id'], ['palettes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movements_action_timestamp', 'palette_movements', ['action', 'timestamp'], unique=False)
    op.create_index('ix_movements_expedition_timestamp', 'palette_movements', ['expedition_id', 'timestamp'], unique=False)
    op.create_index('ix_movements_palette_timestamp', 'palette_movements', ['palette_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_palette_movements_action'), 'palette_movements', ['action'], unique=False)
    op.create_index(op.f('ix_palette_movements_expedition_id'), 'palette_movements', ['expedition_id'], unique=False)
    op.create_index(op.f('ix_palette_movements_id'), 'palette_movements', ['id'], unique=False)
    op.create_index(op.f('ix_palette_movements_palette_id'), 'palette_movements', ['palette_id'], unique=False)
    op.create_index(op.f('ix_palette_movements_timestamp'), 'palette_movements', ['timestamp'], unique=False)
    op.create_index(op.f('ix_palette_movements_user_id'), 'palette_movements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_palette_movements_user_id'), table_name='palette_movements')
    op.drop_index(op.f('ix_palette_movements_timestamp'), table_name='palette_movements')
    op.drop_index(op.f('ix_palette_movements_palette_id'), table_name='palette_movements')
    op.drop_index(op.f('ix_palette_movements_id'), table_name='palette_movements')
    op.drop_index(op.f('ix_palette_movements_expedition_id'), table_name='palette_movements')
    op.drop_index(op.f('ix_palette_movements_action'), table_name='palette_movements')
    op.drop_index('ix_movements_palette_timestamp', table_name='palette_movements')
    op.drop_index('ix_movements_expedition_timestamp', table_name='palette_movements')
    op.drop_index('ix_movements_action_timestamp', table_name='palette_movements')
    op.drop_table('palette_movements')
    op.drop_index('ix_notifications_type_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index('ix_notifications_status_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sent_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_email'), table_name='notifications')
    op.drop_index('ix_notifications_recipient', table_name='notifications')
    op.drop_index(op.f('ix_notifications_palette_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_expedition_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_palettes_type_status', table_name='palettes')
    op.drop_index(op.f('ix_palettes_type'), table_name='palettes')
    op.drop_index(op.f('ix_palettes_status'), table_name='palettes')
    op.drop_index(op.f('ix_palettes_rfid_tag'), table_name='palettes')
    op.drop_index('ix_palettes_rfid_status', table_name='palettes')
    op.drop_index(op.f('ix_palettes_id'), table_name='palettes')
    op.drop_index('ix_palettes_expedition', table_name='palettes')
    op.drop_index(op.f('ix_palettes_current_expedition_id'), table_name='palettes')
    op.drop_index(op.f('ix_palettes_created_by_id'), table_name='palettes')
    op.drop_index(op.f('ix_palettes_created_at'), table_name='palettes')
    op.drop_table('palettes')
    op.drop_index(op.f('ix_expeditions_validated_by_id'), table_name='expeditions')
    op.drop_index('ix_expeditions_status_dates', table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_status'), table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_reference_number'), table_name='expeditions')
    op.drop_index('ix_expeditions_ref_status', table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_id'), table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_eta'), table_name='expeditions')
    op.drop_index('ix_expeditions_dates', table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_date_departure'), table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_date_delivery'), table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_date_creation'), table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_created_by_id'), table_name='expeditions')
    op.drop_index(op.f('ix_expeditions_created_at'), table_name='expeditions')
    op.drop_table('expeditions')
    op.drop_index('ix_audit_user_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_success_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_success'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_endpoint'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_action_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
