"""sync_local_state

Revision ID: 1712b3ff53b4
Revises: add_logo_to_groupe
Create Date: 2025-11-28 12:53:06.066286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1712b3ff53b4'
down_revision: Union[str, Sequence[str], None] = 'add_logo_to_groupe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bons_enlevement', 'id',
               existing_type=sa.UUID(),
               comment="Unique bon d'enlèvement identifier",
               existing_comment='Unique identifier for the Bon d Enlèvement',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'numero_bon',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique bon number',
               existing_comment='Unique number of the Bon d Enlèvement',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='Internal reference',
               existing_comment='Internal reference for the Bon d Enlèvement')
    op.alter_column('bons_enlevement', 'centre_remplisseur_id',
               existing_type=sa.UUID(),
               comment='FK to centres_remplisseurs',
               existing_comment='Foreign key to the CentreRemplisseur model',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'grossiste_id',
               existing_type=sa.UUID(),
               comment='FK to partners (commissioning grossiste)',
               existing_comment='Foreign key to the Partner model (ordering grossiste)',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'depot_principal_id',
               existing_type=sa.UUID(),
               comment="FK to depots (grossiste's final depot)",
               existing_comment='Foreign key to the Depot model (final destination depot)',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'vehicule_immatriculation',
               existing_type=sa.VARCHAR(length=50),
               comment='Vehicle registration',
               existing_comment='Vehicle registration number',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'chauffeur_nom',
               existing_type=sa.VARCHAR(length=255),
               comment='Driver name',
               existing_comment='Name of the driver',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'chauffeur_societe',
               existing_type=sa.VARCHAR(length=255),
               comment='Driver company',
               existing_comment='Company of the driver',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'chauffeur_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Driver phone',
               existing_comment='Phone number of the driver',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               comment='Creation date',
               existing_comment='Date of creation of the Bon d Enlèvement',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'date_validation',
               existing_type=postgresql.TIMESTAMP(),
               comment='Validation date by centre',
               existing_comment='Date of validation by the filling center',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'date_chargement',
               existing_type=postgresql.TIMESTAMP(),
               comment='Loading start date',
               existing_comment='Start date of loading',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'date_depart',
               existing_type=postgresql.TIMESTAMP(),
               comment='Departure date from centre',
               existing_comment='Departure date from the filling center',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'date_arrivee_finale',
               existing_type=postgresql.TIMESTAMP(),
               comment='Arrival date at main depot',
               existing_comment='Final arrival date at the main depot',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'status',
               existing_type=postgresql.ENUM('CREATION', 'VALIDE', 'EN_CHARGEMENT', 'EN_ROUTE', 'EN_LIVRAISON', 'TERMINE', 'ANNULE', name='bon_enlevement_status'),
               comment='Current status',
               existing_comment='Current status of the Bon d Enlèvement workflow',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'observations',
               existing_type=sa.VARCHAR(length=1000),
               comment='Observations',
               existing_comment='Additional observations',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'instructions_livraison',
               existing_type=sa.VARCHAR(length=1000),
               comment='Delivery instructions',
               existing_comment='Special delivery instructions',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'validateur_centre_id',
               existing_type=sa.UUID(),
               comment='FK to users (who validated at centre)',
               existing_comment='User who validated the Bon d Enlèvement at the filling center',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'recepteur_final_id',
               existing_type=sa.UUID(),
               comment='FK to users (who received at main depot)',
               existing_comment='User who received the final delivery at the main depot',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'otp_code',
               existing_type=sa.VARCHAR(length=10),
               comment='OTP code for security',
               existing_comment='One-time password for delivery validation',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'palette_count',
               existing_type=sa.INTEGER(),
               comment='Number of palettes in bon',
               existing_comment='Number of palettes',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bons_enlevement', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.drop_constraint('bons_enlevement_numero_bon_key', 'bons_enlevement', type_='unique')
    op.drop_index('ix_bons_enlevement_dates', table_name='bons_enlevement')
    op.drop_index('ix_bons_enlevement_grossiste_centre', table_name='bons_enlevement')
    op.drop_index('ix_bons_enlevement_numero_bon_status', table_name='bons_enlevement')
    op.drop_index('ix_bons_enlevement_numero_bon', table_name='bons_enlevement')
    op.create_index(op.f('ix_bons_enlevement_numero_bon'), 'bons_enlevement', ['numero_bon'], unique=True)
    op.create_index('ix_bons_enl_centre', 'bons_enlevement', ['centre_remplisseur_id', 'status'], unique=False)
    op.create_index('ix_bons_enl_dates', 'bons_enlevement', ['date_creation', 'date_depart'], unique=False)
    op.create_index('ix_bons_enl_grossiste', 'bons_enlevement', ['grossiste_id', 'status'], unique=False)
    op.create_index('ix_bons_enl_numero_status', 'bons_enlevement', ['numero_bon', 'status'], unique=False)
    op.create_index(op.f('ix_bons_enlevement_created_at'), 'bons_enlevement', ['created_at'], unique=False)
    op.create_index(op.f('ix_bons_enlevement_depot_principal_id'), 'bons_enlevement', ['depot_principal_id'], unique=False)
    op.create_index(op.f('ix_bons_enlevement_recepteur_final_id'), 'bons_enlevement', ['recepteur_final_id'], unique=False)
    op.create_index(op.f('ix_bons_enlevement_reference'), 'bons_enlevement', ['reference'], unique=True)
    op.create_index(op.f('ix_bons_enlevement_validateur_centre_id'), 'bons_enlevement', ['validateur_centre_id'], unique=False)
    op.alter_column('bons_reception_retour', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('bons_reception_retour', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.drop_constraint('bons_reception_retour_numero_bl_key', 'bons_reception_retour', type_='unique')
    op.drop_constraint('bons_reception_retour_numero_reception_key', 'bons_reception_retour', type_='unique')
    op.drop_index('ix_bons_reception_retour_numero_bl', table_name='bons_reception_retour')
    op.create_index(op.f('ix_bons_reception_retour_numero_bl'), 'bons_reception_retour', ['numero_bl'], unique=True)
    op.drop_index('ix_bons_reception_retour_numero_reception', table_name='bons_reception_retour')
    op.create_index(op.f('ix_bons_reception_retour_numero_reception'), 'bons_reception_retour', ['numero_reception'], unique=True)
    op.create_index(op.f('ix_bons_reception_retour_created_at'), 'bons_reception_retour', ['created_at'], unique=False)
    op.create_index(op.f('ix_bons_reception_retour_depot_depart_id'), 'bons_reception_retour', ['depot_depart_id'], unique=False)
    op.alter_column('centres_remplisseurs', 'id',
               existing_type=sa.UUID(),
               comment='Unique centre remplisseur identifier',
               existing_comment='Unique identifier for the filling center',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Centre name',
               existing_comment='Name of the filling center',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique code',
               existing_comment='Unique code for the filling center',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'grand_distributeur_id',
               existing_type=sa.UUID(),
               comment='FK to grand_distributeurs',
               existing_comment='Foreign key to the GrandDistributeur model',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               comment='Street address',
               existing_comment='Physical address of the filling center')
    op.alter_column('centres_remplisseurs', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='City',
               existing_comment='City where the filling center is located')
    op.alter_column('centres_remplisseurs', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Postal code',
               existing_comment='Postal code of the filling center',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment='Country',
               existing_comment='Country of the filling center',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS latitude',
               existing_comment='GPS latitude of the filling center',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS longitude',
               existing_comment='GPS longitude of the filling center',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number',
               existing_comment='Phone number of the filling center',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address',
               existing_comment='Email address of the filling center',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'contact_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Contact person name',
               existing_comment='Name of the contact person at the filling center',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Contact person phone',
               existing_comment='Phone number of the contact person at the filling center',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether centre is active',
               existing_comment='Whether the filling center is active',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional notes',
               existing_comment='Additional notes about the filling center',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.drop_constraint('centres_remplisseurs_code_key', 'centres_remplisseurs', type_='unique')
    op.drop_constraint('centres_remplisseurs_email_key', 'centres_remplisseurs', type_='unique')
    op.drop_index('ix_centres_remplisseurs_code', table_name='centres_remplisseurs')
    op.create_index(op.f('ix_centres_remplisseurs_code'), 'centres_remplisseurs', ['code'], unique=True)
    op.create_index('ix_centres_grand_dist', 'centres_remplisseurs', ['grand_distributeur_id', 'is_active'], unique=False)
    op.create_index('ix_centres_location', 'centres_remplisseurs', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_centres_name_active', 'centres_remplisseurs', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_centres_remplisseurs_created_at'), 'centres_remplisseurs', ['created_at'], unique=False)
    op.create_index(op.f('ix_centres_remplisseurs_email'), 'centres_remplisseurs', ['email'], unique=False)
    op.create_index(op.f('ix_centres_remplisseurs_is_active'), 'centres_remplisseurs', ['is_active'], unique=False)
    op.create_index(op.f('ix_centres_remplisseurs_phone'), 'centres_remplisseurs', ['phone'], unique=False)
    op.alter_column('collectes_vides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('collectes_vides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.create_index(op.f('ix_collectes_vides_bon_enlevement_id'), 'collectes_vides', ['bon_enlevement_id'], unique=False)
    op.create_index(op.f('ix_collectes_vides_created_at'), 'collectes_vides', ['created_at'], unique=False)
    op.create_index(op.f('ix_collectes_vides_depot_id'), 'collectes_vides', ['depot_id'], unique=False)
    op.create_index(op.f('ix_collectes_vides_livraison_detail_id'), 'collectes_vides', ['livraison_detail_id'], unique=False)
    op.alter_column('contacts', 'id',
               existing_type=sa.UUID(),
               comment='Unique contact identifier',
               existing_nullable=False)
    op.alter_column('contacts', 'partner_id',
               existing_type=sa.UUID(),
               comment='Partner this contact belongs to',
               existing_nullable=False)
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Contact first name',
               existing_nullable=False)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Contact last name',
               existing_nullable=False)
    op.alter_column('contacts', 'position',
               existing_type=sa.VARCHAR(length=100),
               comment='Job position/title',
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number',
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address',
               existing_nullable=True)
    op.alter_column('contacts', 'is_primary',
               existing_type=sa.BOOLEAN(),
               comment='Whether this is the primary contact',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contacts', 'notes',
               existing_type=sa.VARCHAR(length=500),
               comment='Additional notes',
               existing_nullable=True)
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.alter_column('depots', 'id',
               existing_type=sa.UUID(),
               comment='Unique depot identifier',
               existing_comment='Unique identifier for the depot',
               existing_nullable=False)
    op.alter_column('depots', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Depot name',
               existing_comment='Name of the depot',
               existing_nullable=False)
    op.alter_column('depots', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='Unique code',
               existing_comment='Unique code for the depot')
    op.alter_column('depots', 'partner_id',
               existing_type=sa.UUID(),
               comment='FK to partners (grossiste or revendeur)',
               existing_comment='Foreign key to the Partner model',
               existing_nullable=False)
    op.alter_column('depots', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               comment='Street address',
               existing_comment='Physical address of the depot')
    op.alter_column('depots', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='City',
               existing_comment='City where the depot is located')
    op.alter_column('depots', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Postal code',
               existing_comment='Postal code of the depot',
               existing_nullable=True)
    op.alter_column('depots', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS latitude',
               existing_comment='GPS latitude of the depot',
               existing_nullable=True)
    op.alter_column('depots', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS longitude',
               existing_comment='GPS longitude of the depot',
               existing_nullable=True)
    op.alter_column('depots', 'contact_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Contact person name',
               existing_comment='Name of the contact person at the depot',
               existing_nullable=True)
    op.alter_column('depots', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Contact person phone',
               existing_comment='Phone number of the contact person at the depot',
               existing_nullable=True)
    op.alter_column('depots', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether depot is active',
               existing_comment='Whether the depot is active',
               existing_nullable=False)
    op.alter_column('depots', 'is_main_depot',
               existing_type=sa.BOOLEAN(),
               comment='Whether this is the main depot of the partner',
               existing_comment='Indicates if this is the main depot for the partner',
               existing_nullable=False)
    op.alter_column('depots', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional notes',
               existing_comment='Additional notes about the depot',
               existing_nullable=True)
    op.alter_column('depots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('depots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.drop_constraint('depots_code_key', 'depots', type_='unique')
    op.drop_index('ix_depots_code', table_name='depots')
    op.create_index(op.f('ix_depots_code'), 'depots', ['code'], unique=True)
    op.create_index(op.f('ix_depots_created_at'), 'depots', ['created_at'], unique=False)
    op.create_index(op.f('ix_depots_is_active'), 'depots', ['is_active'], unique=False)
    op.create_index(op.f('ix_depots_is_main_depot'), 'depots', ['is_main_depot'], unique=False)
    op.alter_column('details_retour', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('details_retour', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.create_index(op.f('ix_details_retour_bon_reception_retour_id'), 'details_retour', ['bon_reception_retour_id'], unique=False)
    op.create_index(op.f('ix_details_retour_created_at'), 'details_retour', ['created_at'], unique=False)
    op.alter_column('expeditions', 'grossiste_id',
               existing_type=sa.UUID(),
               comment='Grossiste (partner) ID',
               existing_nullable=True)
    op.alter_column('expeditions', 'driver_id',
               existing_type=sa.UUID(),
               comment='Driver (chauffeur) user ID',
               existing_nullable=True)
    op.alter_column('expeditions', 'contact_id',
               existing_type=sa.UUID(),
               comment='Contact ID (e.g., contact at grossiste, driver contact, etc.)',
               existing_nullable=True)
    op.alter_column('expeditions', 'libelle',
               existing_type=sa.VARCHAR(length=255),
               comment='Libellé (label) for the expedition',
               existing_nullable=True)
    op.add_column('grand_distributeurs', sa.Column('postal_code', sa.String(length=20), nullable=True, comment='Postal code'))
    op.add_column('grand_distributeurs', sa.Column('country', sa.String(length=100), nullable=True, comment='Country'))
    op.add_column('grand_distributeurs', sa.Column('contact_name', sa.String(length=255), nullable=True, comment='Contact person name'))
    op.add_column('grand_distributeurs', sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='Contact person phone'))
    op.alter_column('grand_distributeurs', 'id',
               existing_type=sa.UUID(),
               comment='Unique grand distributeur identifier',
               existing_comment='Unique identifier for the grand distributor',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Grand distributeur name',
               existing_comment='Name of the grand distributor',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique code',
               existing_comment='Unique code for the grand distributor',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'groupe_id',
               existing_type=sa.UUID(),
               comment='FK to groupes',
               existing_comment='Foreign key to the Groupe model',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment='Street address',
               existing_comment='Physical address of the grand distributor',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='City',
               existing_comment='City where the grand distributor is located',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number',
               existing_comment='Phone number of the grand distributor',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address',
               existing_comment='Email address of the grand distributor',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether grand distributeur is active',
               existing_comment='Whether the grand distributor is active',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional notes',
               existing_comment='Additional notes about the grand distributor',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.drop_constraint('grand_distributeurs_code_key', 'grand_distributeurs', type_='unique')
    op.drop_constraint('grand_distributeurs_email_key', 'grand_distributeurs', type_='unique')
    op.drop_index('ix_grand_distributeurs_code', table_name='grand_distributeurs')
    op.create_index(op.f('ix_grand_distributeurs_code'), 'grand_distributeurs', ['code'], unique=True)
    op.create_index('ix_grand_dist_groupe', 'grand_distributeurs', ['groupe_id', 'is_active'], unique=False)
    op.create_index('ix_grand_dist_name_active', 'grand_distributeurs', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_grand_distributeurs_created_at'), 'grand_distributeurs', ['created_at'], unique=False)
    op.create_index(op.f('ix_grand_distributeurs_email'), 'grand_distributeurs', ['email'], unique=False)
    op.create_index(op.f('ix_grand_distributeurs_is_active'), 'grand_distributeurs', ['is_active'], unique=False)
    op.create_index(op.f('ix_grand_distributeurs_phone'), 'grand_distributeurs', ['phone'], unique=False)
    op.alter_column('groupes', 'id',
               existing_type=sa.UUID(),
               comment='Unique groupe identifier',
               existing_comment='Unique identifier for the group',
               existing_nullable=False)
    op.alter_column('groupes', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Groupe name',
               existing_comment='Name of the group',
               existing_nullable=False)
    op.alter_column('groupes', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique code',
               existing_comment='Unique code for the group',
               existing_nullable=False)
    op.alter_column('groupes', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment='Street address',
               existing_comment='Physical address of the group',
               existing_nullable=True)
    op.alter_column('groupes', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='City',
               existing_comment='City where the group is located',
               existing_nullable=True)
    op.alter_column('groupes', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number',
               existing_comment='Phone number of the group',
               existing_nullable=True)
    op.alter_column('groupes', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address',
               existing_comment='Email address of the group',
               existing_nullable=True)
    op.alter_column('groupes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether groupe is active',
               existing_comment='Whether the group is active',
               existing_nullable=False)
    op.alter_column('groupes', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional notes',
               existing_comment='Additional notes about the group',
               existing_nullable=True)
    op.alter_column('groupes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('groupes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.drop_constraint('groupes_code_key', 'groupes', type_='unique')
    op.drop_constraint('groupes_email_key', 'groupes', type_='unique')
    op.drop_index('ix_groupes_code', table_name='groupes')
    op.create_index(op.f('ix_groupes_code'), 'groupes', ['code'], unique=True)
    op.create_index('ix_groupes_code_active', 'groupes', ['code', 'is_active'], unique=False)
    op.create_index(op.f('ix_groupes_created_at'), 'groupes', ['created_at'], unique=False)
    op.create_index(op.f('ix_groupes_email'), 'groupes', ['email'], unique=False)
    op.create_index(op.f('ix_groupes_is_active'), 'groupes', ['is_active'], unique=False)
    op.create_index('ix_groupes_name_active', 'groupes', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_groupes_phone'), 'groupes', ['phone'], unique=False)
    op.alter_column('livraisons_details', 'revendeur_id',
               existing_type=sa.UUID(),
               comment='FK to partners (if revendeur, else NULL for grossiste)',
               existing_comment='FK to partners (if revendeur)',
               existing_nullable=True)
    op.alter_column('livraisons_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('livraisons_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.create_index(op.f('ix_livraisons_details_bon_enlevement_id'), 'livraisons_details', ['bon_enlevement_id'], unique=False)
    op.create_index(op.f('ix_livraisons_details_created_at'), 'livraisons_details', ['created_at'], unique=False)
    op.create_index(op.f('ix_livraisons_details_depot_id'), 'livraisons_details', ['depot_id'], unique=False)
    op.create_index(op.f('ix_livraisons_details_revendeur_id'), 'livraisons_details', ['revendeur_id'], unique=False)
    op.drop_index('ix_movements_expedition_timestamp', table_name='palette_movements')
    op.drop_index('ix_palette_movements_expedition_id', table_name='palette_movements')
    op.create_index(op.f('ix_palette_movements_bon_enlevement_id'), 'palette_movements', ['bon_enlevement_id'], unique=False)
    op.create_index(op.f('ix_palette_movements_bon_reception_retour_id'), 'palette_movements', ['bon_reception_retour_id'], unique=False)
    op.create_index(op.f('ix_palette_movements_centre_remplisseur_id'), 'palette_movements', ['centre_remplisseur_id'], unique=False)
    op.create_index(op.f('ix_palette_movements_depot_id'), 'palette_movements', ['depot_id'], unique=False)
    op.create_index(op.f('ix_palette_movements_livraison_detail_id'), 'palette_movements', ['livraison_detail_id'], unique=False)
    op.drop_constraint('palette_movements_expedition_id_fkey', 'palette_movements', type_='foreignkey')
    op.drop_column('palette_movements', 'expedition_id')
    op.alter_column('palettes', 'serial_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Human-readable serial number (e.g., PAL-2025-00001)',
               existing_nullable=False)
    op.alter_column('palettes', 'reference_code',
               existing_type=sa.VARCHAR(length=50),
               comment='Code de référence personnalisé (saisie manuelle)',
               existing_nullable=True)
    op.alter_column('palettes', 'rfid_tag_id',
               existing_type=sa.UUID(),
               comment='ID du tag RFID assigné à cette palette',
               existing_nullable=True)
    op.alter_column('palettes', 'capacity',
               existing_type=sa.INTEGER(),
               comment='Capacité en nombre de bouteilles possibles',
               existing_nullable=True)
    op.alter_column('palettes', 'manufacturing_date',
               existing_type=sa.DATE(),
               comment='Date de fabrication de la palette',
               existing_nullable=True)
    op.alter_column('palettes', 'current_partner_id',
               existing_type=sa.UUID(),
               comment='ID du partenaire (grossiste) chez qui se trouve actuellement la palette',
               existing_nullable=True)
    op.drop_index('ix_palettes_current_expedition_id', table_name='palettes')
    op.drop_index('ix_palettes_expedition', table_name='palettes')
    op.drop_index('ix_palettes_rfid_tag_id_status', table_name='palettes')
    op.drop_constraint('uq_palettes_reference_code', 'palettes', type_='unique')
    op.drop_constraint('uq_palettes_serial_number', 'palettes', type_='unique')
    op.drop_index('ix_palettes_reference_code', table_name='palettes')
    op.create_index(op.f('ix_palettes_reference_code'), 'palettes', ['reference_code'], unique=True)
    op.drop_index('ix_palettes_serial_number', table_name='palettes')
    op.create_index(op.f('ix_palettes_serial_number'), 'palettes', ['serial_number'], unique=True)
    op.create_index(op.f('ix_palettes_bon_enlevement_actuel_id'), 'palettes', ['bon_enlevement_actuel_id'], unique=False)
    op.create_index(op.f('ix_palettes_bon_retour_actuel_id'), 'palettes', ['bon_retour_actuel_id'], unique=False)
    op.create_index(op.f('ix_palettes_current_centre_remplisseur_id'), 'palettes', ['current_centre_remplisseur_id'], unique=False)
    op.create_index(op.f('ix_palettes_current_depot_id'), 'palettes', ['current_depot_id'], unique=False)
    op.create_index('ix_palettes_rfid_status', 'palettes', ['rfid_tag_id', 'status'], unique=False)
    op.drop_constraint('palettes_current_expedition_id_fkey', 'palettes', type_='foreignkey')
    op.drop_column('palettes', 'current_expedition_id')
    op.alter_column('partners', 'id',
               existing_type=sa.UUID(),
               comment='Unique partner identifier',
               existing_nullable=False)
    op.alter_column('partners', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Partner name (company name)',
               existing_nullable=False)
    op.alter_column('partners', 'type',
               existing_type=postgresql.ENUM('GROSSISTE', 'FOURNISSEUR', 'TRANSPORTEUR', 'AUTRE', 'REVENDEUR', name='partner_type'),
               comment='Partner type',
               existing_nullable=False,
               existing_server_default=sa.text("'GROSSISTE'::partner_type"))
    op.alter_column('partners', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique code (client ID)',
               existing_comment='Unique client code for the partner',
               existing_nullable=True)
    op.alter_column('partners', 'parent_grossiste_id',
               existing_type=sa.UUID(),
               comment='FK to parent grossiste (for REVENDEUR only)',
               existing_comment='For REVENDEUR type, ID of the parent grossiste',
               existing_nullable=True)
    op.alter_column('partners', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment='Street address',
               existing_nullable=True)
    op.alter_column('partners', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='City',
               existing_nullable=True)
    op.alter_column('partners', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Postal code',
               existing_nullable=True)
    op.alter_column('partners', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment='Country',
               existing_nullable=True,
               existing_server_default=sa.text("'France'::character varying"))
    op.alter_column('partners', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number',
               existing_nullable=True)
    op.alter_column('partners', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address',
               existing_nullable=True)
    op.alter_column('partners', 'contact_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Contact person name',
               existing_comment='Name of the primary contact person for the partner',
               existing_nullable=True)
    op.alter_column('partners', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Contact person phone',
               existing_comment='Phone number of the primary contact person for the partner',
               existing_nullable=True)
    op.alter_column('partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether partner is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('partners', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional notes',
               existing_nullable=True)
    op.alter_column('partners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('partners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.create_index(op.f('ix_partners_created_at'), 'partners', ['created_at'], unique=False)
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_index(op.f('ix_partners_is_active'), 'partners', ['is_active'], unique=False)
    op.create_index('ix_partners_parent', 'partners', ['parent_grossiste_id'], unique=False)
    op.create_index(op.f('ix_partners_type'), 'partners', ['type'], unique=False)
    op.alter_column('rfid_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rfid_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_rfid_tags_created_by_id', table_name='rfid_tags')
    op.drop_constraint('rfid_tags_tag_number_key', 'rfid_tags', type_='unique')
    op.create_index(op.f('ix_rfid_tags_tag_number'), 'rfid_tags', ['tag_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfid_tags_tag_number'), table_name='rfid_tags')
    op.create_unique_constraint('rfid_tags_tag_number_key', 'rfid_tags', ['tag_number'])
    op.create_index('ix_rfid_tags_created_by_id', 'rfid_tags', ['created_by_id'], unique=False)
    op.alter_column('rfid_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rfid_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_partners_type'), table_name='partners')
    op.drop_index('ix_partners_parent', table_name='partners')
    op.drop_index(op.f('ix_partners_is_active'), table_name='partners')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_index(op.f('ix_partners_created_at'), table_name='partners')
    op.alter_column('partners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('partners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('partners', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether partner is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('partners', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number of the primary contact person for the partner',
               existing_comment='Contact person phone',
               existing_nullable=True)
    op.alter_column('partners', 'contact_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the primary contact person for the partner',
               existing_comment='Contact person name',
               existing_nullable=True)
    op.alter_column('partners', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email address',
               existing_nullable=True)
    op.alter_column('partners', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Phone number',
               existing_nullable=True)
    op.alter_column('partners', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Country',
               existing_nullable=True,
               existing_server_default=sa.text("'France'::character varying"))
    op.alter_column('partners', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Postal code',
               existing_nullable=True)
    op.alter_column('partners', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='City',
               existing_nullable=True)
    op.alter_column('partners', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Street address',
               existing_nullable=True)
    op.alter_column('partners', 'parent_grossiste_id',
               existing_type=sa.UUID(),
               comment='For REVENDEUR type, ID of the parent grossiste',
               existing_comment='FK to parent grossiste (for REVENDEUR only)',
               existing_nullable=True)
    op.alter_column('partners', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique client code for the partner',
               existing_comment='Unique code (client ID)',
               existing_nullable=True)
    op.alter_column('partners', 'type',
               existing_type=postgresql.ENUM('GROSSISTE', 'FOURNISSEUR', 'TRANSPORTEUR', 'AUTRE', 'REVENDEUR', name='partner_type'),
               comment=None,
               existing_comment='Partner type',
               existing_nullable=False,
               existing_server_default=sa.text("'GROSSISTE'::partner_type"))
    op.alter_column('partners', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Partner name (company name)',
               existing_nullable=False)
    op.alter_column('partners', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique partner identifier',
               existing_nullable=False)
    op.add_column('palettes', sa.Column('current_expedition_id', sa.UUID(), autoincrement=False, nullable=True, comment='Current expedition if in transit'))
    op.create_foreign_key('palettes_current_expedition_id_fkey', 'palettes', 'expeditions', ['current_expedition_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_palettes_rfid_status', table_name='palettes')
    op.drop_index(op.f('ix_palettes_current_depot_id'), table_name='palettes')
    op.drop_index(op.f('ix_palettes_current_centre_remplisseur_id'), table_name='palettes')
    op.drop_index(op.f('ix_palettes_bon_retour_actuel_id'), table_name='palettes')
    op.drop_index(op.f('ix_palettes_bon_enlevement_actuel_id'), table_name='palettes')
    op.drop_index(op.f('ix_palettes_serial_number'), table_name='palettes')
    op.create_index('ix_palettes_serial_number', 'palettes', ['serial_number'], unique=False)
    op.drop_index(op.f('ix_palettes_reference_code'), table_name='palettes')
    op.create_index('ix_palettes_reference_code', 'palettes', ['reference_code'], unique=False)
    op.create_unique_constraint('uq_palettes_serial_number', 'palettes', ['serial_number'])
    op.create_unique_constraint('uq_palettes_reference_code', 'palettes', ['reference_code'])
    op.create_index('ix_palettes_rfid_tag_id_status', 'palettes', ['rfid_tag_id', 'status'], unique=False)
    op.create_index('ix_palettes_expedition', 'palettes', ['current_expedition_id'], unique=False)
    op.create_index('ix_palettes_current_expedition_id', 'palettes', ['current_expedition_id'], unique=False)
    op.alter_column('palettes', 'current_partner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID du partenaire (grossiste) chez qui se trouve actuellement la palette',
               existing_nullable=True)
    op.alter_column('palettes', 'manufacturing_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date de fabrication de la palette',
               existing_nullable=True)
    op.alter_column('palettes', 'capacity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Capacité en nombre de bouteilles possibles',
               existing_nullable=True)
    op.alter_column('palettes', 'rfid_tag_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID du tag RFID assigné à cette palette',
               existing_nullable=True)
    op.alter_column('palettes', 'reference_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Code de référence personnalisé (saisie manuelle)',
               existing_nullable=True)
    op.alter_column('palettes', 'serial_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Human-readable serial number (e.g., PAL-2025-00001)',
               existing_nullable=False)
    op.add_column('palette_movements', sa.Column('expedition_id', sa.UUID(), autoincrement=False, nullable=True, comment='Related expedition (optional)'))
    op.create_foreign_key('palette_movements_expedition_id_fkey', 'palette_movements', 'expeditions', ['expedition_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_palette_movements_livraison_detail_id'), table_name='palette_movements')
    op.drop_index(op.f('ix_palette_movements_depot_id'), table_name='palette_movements')
    op.drop_index(op.f('ix_palette_movements_centre_remplisseur_id'), table_name='palette_movements')
    op.drop_index(op.f('ix_palette_movements_bon_reception_retour_id'), table_name='palette_movements')
    op.drop_index(op.f('ix_palette_movements_bon_enlevement_id'), table_name='palette_movements')
    op.create_index('ix_palette_movements_expedition_id', 'palette_movements', ['expedition_id'], unique=False)
    op.create_index('ix_movements_expedition_timestamp', 'palette_movements', ['expedition_id', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_livraisons_details_revendeur_id'), table_name='livraisons_details')
    op.drop_index(op.f('ix_livraisons_details_depot_id'), table_name='livraisons_details')
    op.drop_index(op.f('ix_livraisons_details_created_at'), table_name='livraisons_details')
    op.drop_index(op.f('ix_livraisons_details_bon_enlevement_id'), table_name='livraisons_details')
    op.alter_column('livraisons_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('livraisons_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('livraisons_details', 'revendeur_id',
               existing_type=sa.UUID(),
               comment='FK to partners (if revendeur)',
               existing_comment='FK to partners (if revendeur, else NULL for grossiste)',
               existing_nullable=True)
    op.drop_index(op.f('ix_groupes_phone'), table_name='groupes')
    op.drop_index('ix_groupes_name_active', table_name='groupes')
    op.drop_index(op.f('ix_groupes_is_active'), table_name='groupes')
    op.drop_index(op.f('ix_groupes_email'), table_name='groupes')
    op.drop_index(op.f('ix_groupes_created_at'), table_name='groupes')
    op.drop_index('ix_groupes_code_active', table_name='groupes')
    op.drop_index(op.f('ix_groupes_code'), table_name='groupes')
    op.create_index('ix_groupes_code', 'groupes', ['code'], unique=False)
    op.create_unique_constraint('groupes_email_key', 'groupes', ['email'])
    op.create_unique_constraint('groupes_code_key', 'groupes', ['code'])
    op.alter_column('groupes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('groupes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('groupes', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional notes about the group',
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('groupes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether the group is active',
               existing_comment='Whether groupe is active',
               existing_nullable=False)
    op.alter_column('groupes', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address of the group',
               existing_comment='Email address',
               existing_nullable=True)
    op.alter_column('groupes', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number of the group',
               existing_comment='Phone number',
               existing_nullable=True)
    op.alter_column('groupes', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='City where the group is located',
               existing_comment='City',
               existing_nullable=True)
    op.alter_column('groupes', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment='Physical address of the group',
               existing_comment='Street address',
               existing_nullable=True)
    op.alter_column('groupes', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique code for the group',
               existing_comment='Unique code',
               existing_nullable=False)
    op.alter_column('groupes', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the group',
               existing_comment='Groupe name',
               existing_nullable=False)
    op.alter_column('groupes', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the group',
               existing_comment='Unique groupe identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_grand_distributeurs_phone'), table_name='grand_distributeurs')
    op.drop_index(op.f('ix_grand_distributeurs_is_active'), table_name='grand_distributeurs')
    op.drop_index(op.f('ix_grand_distributeurs_email'), table_name='grand_distributeurs')
    op.drop_index(op.f('ix_grand_distributeurs_created_at'), table_name='grand_distributeurs')
    op.drop_index('ix_grand_dist_name_active', table_name='grand_distributeurs')
    op.drop_index('ix_grand_dist_groupe', table_name='grand_distributeurs')
    op.drop_index(op.f('ix_grand_distributeurs_code'), table_name='grand_distributeurs')
    op.create_index('ix_grand_distributeurs_code', 'grand_distributeurs', ['code'], unique=False)
    op.create_unique_constraint('grand_distributeurs_email_key', 'grand_distributeurs', ['email'])
    op.create_unique_constraint('grand_distributeurs_code_key', 'grand_distributeurs', ['code'])
    op.alter_column('grand_distributeurs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional notes about the grand distributor',
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether the grand distributor is active',
               existing_comment='Whether grand distributeur is active',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address of the grand distributor',
               existing_comment='Email address',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number of the grand distributor',
               existing_comment='Phone number',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='City where the grand distributor is located',
               existing_comment='City',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment='Physical address of the grand distributor',
               existing_comment='Street address',
               existing_nullable=True)
    op.alter_column('grand_distributeurs', 'groupe_id',
               existing_type=sa.UUID(),
               comment='Foreign key to the Groupe model',
               existing_comment='FK to groupes',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique code for the grand distributor',
               existing_comment='Unique code',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the grand distributor',
               existing_comment='Grand distributeur name',
               existing_nullable=False)
    op.alter_column('grand_distributeurs', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the grand distributor',
               existing_comment='Unique grand distributeur identifier',
               existing_nullable=False)
    op.drop_column('grand_distributeurs', 'contact_phone')
    op.drop_column('grand_distributeurs', 'contact_name')
    op.drop_column('grand_distributeurs', 'country')
    op.drop_column('grand_distributeurs', 'postal_code')
    op.alter_column('expeditions', 'libelle',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Libellé (label) for the expedition',
               existing_nullable=True)
    op.alter_column('expeditions', 'contact_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Contact ID (e.g., contact at grossiste, driver contact, etc.)',
               existing_nullable=True)
    op.alter_column('expeditions', 'driver_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Driver (chauffeur) user ID',
               existing_nullable=True)
    op.alter_column('expeditions', 'grossiste_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Grossiste (partner) ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_details_retour_created_at'), table_name='details_retour')
    op.drop_index(op.f('ix_details_retour_bon_reception_retour_id'), table_name='details_retour')
    op.alter_column('details_retour', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('details_retour', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_depots_is_main_depot'), table_name='depots')
    op.drop_index(op.f('ix_depots_is_active'), table_name='depots')
    op.drop_index(op.f('ix_depots_created_at'), table_name='depots')
    op.drop_index(op.f('ix_depots_code'), table_name='depots')
    op.create_index('ix_depots_code', 'depots', ['code'], unique=False)
    op.create_unique_constraint('depots_code_key', 'depots', ['code'])
    op.alter_column('depots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('depots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('depots', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional notes about the depot',
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('depots', 'is_main_depot',
               existing_type=sa.BOOLEAN(),
               comment='Indicates if this is the main depot for the partner',
               existing_comment='Whether this is the main depot of the partner',
               existing_nullable=False)
    op.alter_column('depots', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether the depot is active',
               existing_comment='Whether depot is active',
               existing_nullable=False)
    op.alter_column('depots', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number of the contact person at the depot',
               existing_comment='Contact person phone',
               existing_nullable=True)
    op.alter_column('depots', 'contact_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the contact person at the depot',
               existing_comment='Contact person name',
               existing_nullable=True)
    op.alter_column('depots', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS longitude of the depot',
               existing_comment='GPS longitude',
               existing_nullable=True)
    op.alter_column('depots', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS latitude of the depot',
               existing_comment='GPS latitude',
               existing_nullable=True)
    op.alter_column('depots', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Postal code of the depot',
               existing_comment='Postal code',
               existing_nullable=True)
    op.alter_column('depots', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='City where the depot is located',
               existing_comment='City')
    op.alter_column('depots', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               comment='Physical address of the depot',
               existing_comment='Street address')
    op.alter_column('depots', 'partner_id',
               existing_type=sa.UUID(),
               comment='Foreign key to the Partner model',
               existing_comment='FK to partners (grossiste or revendeur)',
               existing_nullable=False)
    op.alter_column('depots', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='Unique code for the depot',
               existing_comment='Unique code')
    op.alter_column('depots', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the depot',
               existing_comment='Depot name',
               existing_nullable=False)
    op.alter_column('depots', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the depot',
               existing_comment='Unique depot identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.alter_column('contacts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('contacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('contacts', 'notes',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('contacts', 'is_primary',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this is the primary contact',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email address',
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Phone number',
               existing_nullable=True)
    op.alter_column('contacts', 'position',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Job position/title',
               existing_nullable=True)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Contact last name',
               existing_nullable=False)
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Contact first name',
               existing_nullable=False)
    op.alter_column('contacts', 'partner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Partner this contact belongs to',
               existing_nullable=False)
    op.alter_column('contacts', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique contact identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_collectes_vides_livraison_detail_id'), table_name='collectes_vides')
    op.drop_index(op.f('ix_collectes_vides_depot_id'), table_name='collectes_vides')
    op.drop_index(op.f('ix_collectes_vides_created_at'), table_name='collectes_vides')
    op.drop_index(op.f('ix_collectes_vides_bon_enlevement_id'), table_name='collectes_vides')
    op.alter_column('collectes_vides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('collectes_vides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_centres_remplisseurs_phone'), table_name='centres_remplisseurs')
    op.drop_index(op.f('ix_centres_remplisseurs_is_active'), table_name='centres_remplisseurs')
    op.drop_index(op.f('ix_centres_remplisseurs_email'), table_name='centres_remplisseurs')
    op.drop_index(op.f('ix_centres_remplisseurs_created_at'), table_name='centres_remplisseurs')
    op.drop_index('ix_centres_name_active', table_name='centres_remplisseurs')
    op.drop_index('ix_centres_location', table_name='centres_remplisseurs')
    op.drop_index('ix_centres_grand_dist', table_name='centres_remplisseurs')
    op.drop_index(op.f('ix_centres_remplisseurs_code'), table_name='centres_remplisseurs')
    op.create_index('ix_centres_remplisseurs_code', 'centres_remplisseurs', ['code'], unique=False)
    op.create_unique_constraint('centres_remplisseurs_email_key', 'centres_remplisseurs', ['email'])
    op.create_unique_constraint('centres_remplisseurs_code_key', 'centres_remplisseurs', ['code'])
    op.alter_column('centres_remplisseurs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'notes',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional notes about the filling center',
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether the filling center is active',
               existing_comment='Whether centre is active',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number of the contact person at the filling center',
               existing_comment='Contact person phone',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'contact_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the contact person at the filling center',
               existing_comment='Contact person name',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address of the filling center',
               existing_comment='Email address',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number of the filling center',
               existing_comment='Phone number',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS longitude of the filling center',
               existing_comment='GPS longitude',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPS latitude of the filling center',
               existing_comment='GPS latitude',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment='Country of the filling center',
               existing_comment='Country',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Postal code of the filling center',
               existing_comment='Postal code',
               existing_nullable=True)
    op.alter_column('centres_remplisseurs', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='City where the filling center is located',
               existing_comment='City')
    op.alter_column('centres_remplisseurs', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               comment='Physical address of the filling center',
               existing_comment='Street address')
    op.alter_column('centres_remplisseurs', 'grand_distributeur_id',
               existing_type=sa.UUID(),
               comment='Foreign key to the GrandDistributeur model',
               existing_comment='FK to grand_distributeurs',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique code for the filling center',
               existing_comment='Unique code',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the filling center',
               existing_comment='Centre name',
               existing_nullable=False)
    op.alter_column('centres_remplisseurs', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the filling center',
               existing_comment='Unique centre remplisseur identifier',
               existing_nullable=False)
    op.drop_index(op.f('ix_bons_reception_retour_depot_depart_id'), table_name='bons_reception_retour')
    op.drop_index(op.f('ix_bons_reception_retour_created_at'), table_name='bons_reception_retour')
    op.drop_index(op.f('ix_bons_reception_retour_numero_reception'), table_name='bons_reception_retour')
    op.create_index('ix_bons_reception_retour_numero_reception', 'bons_reception_retour', ['numero_reception'], unique=False)
    op.drop_index(op.f('ix_bons_reception_retour_numero_bl'), table_name='bons_reception_retour')
    op.create_index('ix_bons_reception_retour_numero_bl', 'bons_reception_retour', ['numero_bl'], unique=False)
    op.create_unique_constraint('bons_reception_retour_numero_reception_key', 'bons_reception_retour', ['numero_reception'])
    op.create_unique_constraint('bons_reception_retour_numero_bl_key', 'bons_reception_retour', ['numero_bl'])
    op.alter_column('bons_reception_retour', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('bons_reception_retour', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_bons_enlevement_validateur_centre_id'), table_name='bons_enlevement')
    op.drop_index(op.f('ix_bons_enlevement_reference'), table_name='bons_enlevement')
    op.drop_index(op.f('ix_bons_enlevement_recepteur_final_id'), table_name='bons_enlevement')
    op.drop_index(op.f('ix_bons_enlevement_depot_principal_id'), table_name='bons_enlevement')
    op.drop_index(op.f('ix_bons_enlevement_created_at'), table_name='bons_enlevement')
    op.drop_index('ix_bons_enl_numero_status', table_name='bons_enlevement')
    op.drop_index('ix_bons_enl_grossiste', table_name='bons_enlevement')
    op.drop_index('ix_bons_enl_dates', table_name='bons_enlevement')
    op.drop_index('ix_bons_enl_centre', table_name='bons_enlevement')
    op.drop_index(op.f('ix_bons_enlevement_numero_bon'), table_name='bons_enlevement')
    op.create_index('ix_bons_enlevement_numero_bon', 'bons_enlevement', ['numero_bon'], unique=False)
    op.create_index('ix_bons_enlevement_numero_bon_status', 'bons_enlevement', ['numero_bon', 'status'], unique=False)
    op.create_index('ix_bons_enlevement_grossiste_centre', 'bons_enlevement', ['grossiste_id', 'centre_remplisseur_id'], unique=False)
    op.create_index('ix_bons_enlevement_dates', 'bons_enlevement', ['date_depart', 'date_arrivee_finale'], unique=False)
    op.create_unique_constraint('bons_enlevement_numero_bon_key', 'bons_enlevement', ['numero_bon'])
    op.alter_column('bons_enlevement', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'palette_count',
               existing_type=sa.INTEGER(),
               comment='Number of palettes',
               existing_comment='Number of palettes in bon',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bons_enlevement', 'otp_code',
               existing_type=sa.VARCHAR(length=10),
               comment='One-time password for delivery validation',
               existing_comment='OTP code for security',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'recepteur_final_id',
               existing_type=sa.UUID(),
               comment='User who received the final delivery at the main depot',
               existing_comment='FK to users (who received at main depot)',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'validateur_centre_id',
               existing_type=sa.UUID(),
               comment='User who validated the Bon d Enlèvement at the filling center',
               existing_comment='FK to users (who validated at centre)',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'instructions_livraison',
               existing_type=sa.VARCHAR(length=1000),
               comment='Special delivery instructions',
               existing_comment='Delivery instructions',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'observations',
               existing_type=sa.VARCHAR(length=1000),
               comment='Additional observations',
               existing_comment='Observations',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'status',
               existing_type=postgresql.ENUM('CREATION', 'VALIDE', 'EN_CHARGEMENT', 'EN_ROUTE', 'EN_LIVRAISON', 'TERMINE', 'ANNULE', name='bon_enlevement_status'),
               comment='Current status of the Bon d Enlèvement workflow',
               existing_comment='Current status',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'date_arrivee_finale',
               existing_type=postgresql.TIMESTAMP(),
               comment='Final arrival date at the main depot',
               existing_comment='Arrival date at main depot',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'date_depart',
               existing_type=postgresql.TIMESTAMP(),
               comment='Departure date from the filling center',
               existing_comment='Departure date from centre',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'date_chargement',
               existing_type=postgresql.TIMESTAMP(),
               comment='Start date of loading',
               existing_comment='Loading start date',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'date_validation',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date of validation by the filling center',
               existing_comment='Validation date by centre',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'date_creation',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date of creation of the Bon d Enlèvement',
               existing_comment='Creation date',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'chauffeur_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Phone number of the driver',
               existing_comment='Driver phone',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'chauffeur_societe',
               existing_type=sa.VARCHAR(length=255),
               comment='Company of the driver',
               existing_comment='Driver company',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'chauffeur_nom',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the driver',
               existing_comment='Driver name',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'vehicule_immatriculation',
               existing_type=sa.VARCHAR(length=50),
               comment='Vehicle registration number',
               existing_comment='Vehicle registration',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'depot_principal_id',
               existing_type=sa.UUID(),
               comment='Foreign key to the Depot model (final destination depot)',
               existing_comment="FK to depots (grossiste's final depot)",
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'grossiste_id',
               existing_type=sa.UUID(),
               comment='Foreign key to the Partner model (ordering grossiste)',
               existing_comment='FK to partners (commissioning grossiste)',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'centre_remplisseur_id',
               existing_type=sa.UUID(),
               comment='Foreign key to the CentreRemplisseur model',
               existing_comment='FK to centres_remplisseurs',
               existing_nullable=True)
    op.alter_column('bons_enlevement', 'reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='Internal reference for the Bon d Enlèvement',
               existing_comment='Internal reference')
    op.alter_column('bons_enlevement', 'numero_bon',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique number of the Bon d Enlèvement',
               existing_comment='Unique bon number',
               existing_nullable=False)
    op.alter_column('bons_enlevement', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the Bon d Enlèvement',
               existing_comment="Unique bon d'enlèvement identifier",
               existing_nullable=False)
    # ### end Alembic commands ###
