// Bon d'Enlèvement types matching backend schemas

export enum BonEnlevementStatus {
  CREATION = 'CREATION',
  VALIDE = 'VALIDE',
  EN_CHARGEMENT = 'EN_CHARGEMENT',
  EN_ROUTE = 'EN_ROUTE',
  EN_LIVRAISON = 'EN_LIVRAISON',
  TERMINE = 'TERMINE',
  ANNULE = 'ANNULE',
}

export interface BonEnlevement {
  id: string; // UUID
  numero_bon: string;
  reference?: string | null;
  centre_remplisseur_id: string; // UUID
  grossiste_id: string; // UUID
  depot_principal_id?: string | null; // UUID
  vehicule_immatriculation?: string | null;
  chauffeur_nom?: string | null;
  chauffeur_societe?: string | null;
  chauffeur_phone?: string | null;
  status: BonEnlevementStatus;
  date_creation: string;
  date_validation?: string | null;
  date_chargement?: string | null;
  date_depart?: string | null;
  date_arrivee_finale?: string | null;
  date_heure_livraison?: string | null;
  validateur_centre_id?: string | null; // UUID
  recepteur_final_id?: string | null; // UUID
  observations?: string | null;
  instructions_livraison?: string | null;
  created_at: string;
  updated_at: string;
}

export interface BonEnlevementList {
  id: string;
  numero_bon: string;
  status: BonEnlevementStatus;
  centre_remplisseur_id: string;
  grossiste_id: string;
  date_creation: string;
  date_depart?: string | null;
  chauffeur_nom?: string | null;
}

export interface BonEnlevementDetail extends BonEnlevement {
  centre_remplisseur_name?: string | null;
  grossiste_name?: string | null;
  depot_principal_name?: string | null;
  palettes_count?: number | null;
  livraisons_count?: number | null;
  collectes_count?: number | null;
}

export interface BonEnlevementCreate {
  numero_bon?: string; // Auto-generated by backend if not provided
  reference?: string;
  centre_remplisseur_id: string;
  grossiste_id: string;
  depot_principal_id?: string;
  vehicule_immatriculation?: string;
  chauffeur_nom?: string;
  chauffeur_societe?: string;
  chauffeur_phone?: string;
  date_heure_livraison?: string; // ISO datetime string
  palette_ids?: string[]; // Optional list of palette IDs to assign during creation
  observations?: string;
  instructions_livraison?: string;
}

export interface BonEnlevementUpdate {
  reference?: string;
  vehicule_immatriculation?: string;
  chauffeur_nom?: string;
  chauffeur_societe?: string;
  chauffeur_phone?: string;
  date_heure_livraison?: string; // ISO datetime string
  observations?: string;
  instructions_livraison?: string;
}

export interface BonEnlevementValidation {
  validateur_centre_id: string;
  observations?: string;
}

export interface BonEnlevementChargement {
  palette_ids: string[];
  observations?: string;
}

export interface BonEnlevementDepart {
  date_depart?: string;
  observations?: string;
}

export interface BonEnlevementReception {
  recepteur_final_id: string;
  date_arrivee_finale?: string;
  observations?: string;
  otp_code?: string;
}

